# Generated by Django 5.1.4 on 2024-12-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dentist_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='birt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='clinicowner',
            name='birt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clinicowner',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='clinicowner',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='CRO',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='available_slots',
            field=models.IntegerField(default=30, help_text='Duração dos intervalos de consulta em minutos'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='birt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='secretary',
            name='birt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='secretary',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='secretary',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dental_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dentalplan'),
        ),
        migrations.AddField(
            model_name='client',
            name='dental_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dentalplan'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.dentist')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('dentist', 'weekday')},
            },
        ),
    ]
